apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {ca_cert}
    extensions:
    - extension:
        last-update: Wed, 07 Sep 2022 15:49:47 CDT
        provider: minikube.sigs.k8s.io
        version: v1.26.1
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 07 Sep 2022 15:49:47 CDT
        provider: minikube.sigs.k8s.io
        version: v1.26.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate-data: {cl_cert}
    client-key-data: {cl_key}
