apiVersion: v1
kind: Service
metadata:
  name: evidently
spec:
  type: NodePort
  selector:
    app: evidently
  ports:
    - name: mlflow
      protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30011

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidently-neimv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evidently
      owner: neimv
  template:
    metadata:
      labels:
        app: evidently
        owner: neimv
    spec:
      containers:
      - name: evidently-neimv
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_default_region
        image: neimv/evidently
        ports:
        - containerPort: 5005
