apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30012

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-neimv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      owner: neimv
  template:
    metadata:
      labels:
        app: grafana
        owner: neimv
    spec:
      containers:
      - name: grafana-neimv
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_default_region
        image: neimv/grafana
        ports:
        - containerPort: 3000
