apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - name: mlflow
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30009

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-neimv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
      owner: neimv
  template:
    metadata:
      labels:
        app: mlflow
        owner: neimv
    spec:
      containers:
      - name: mlflow-neimv
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_default_region
        - name: MLFLOW_S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: commons
              key: mlflow_s3_endpoint_url
        - name: BUCKET_MLFLOW
          valueFrom:
            secretKeyRef:
              name: commons
              key: bucket_mlflow
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: mlflow
              key: connection_uri
        image: neimv/mlflow:latest
        command: ["mlflow", "server", "--backend-store-uri", "$(DATABASE_URI)", "--default-artifact-root", "s3://$(BUCKET_MLFLOW)/", "--host", "0.0.0.0"]
        ports:
        - containerPort: 5000
