apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-neimv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      owner: neimv
  template:
    metadata:
      labels:
        app: mongo
        owner: neimv
    spec:
      containers:
      - name: mongo-neimv
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_default_region
        - name: MONGO_INITDB_ROOT_USERNAME
          value: fungus
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: fungus
        image: mongo
        ports:
        - containerPort: 27018
