apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9091
      nodePort: 30013

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-neimv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      owner: neimv
  template:
    metadata:
      labels:
        app: prometheus
        owner: neimv
    spec:
      containers:
      - name: prometheus-neimv
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: commons
              key: aws_default_region
        image: neimv/prometheus:latest
        ports:
        - containerPort: 9090
