apiVersion: v1
kind: Secret
metadata:
  name: mlflow
type: Opaque
data:
  username: bWxmbG93
  password: bWxmbG93
  database: bWxmbG93
  host: ZGItbWxmbG93
  connection_uri: cG9zdGdyZXNxbCtwc3ljb3BnMjovL21sZmxvdzptbGZsb3dAZGItbWxmbG93OjU0MzIvbWxmbG93
