apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  type: NodePort
  selector:
    app: ml-service
  ports:
    - name: ml-service
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
