datasets:
  fungus:
    column_mapping:
      categorical_features:
        - 'cap-shape_Convex'
        - 'cap-shape_Bell'
        - 'cap-shape_Sunken'
        - 'cap-shape_Flat'
        - 'cap-shape_Knobbed'
        - 'cap-shape_c'
        - 'cap-surface_Smooth'
        - 'cap-surface_Scaly'
        - 'cap-surface_Fibrous'
        - 'cap-surface_Grooves'
        - 'cap-color_Yellow'
        - 'cap-color_White'
        - 'cap-color_Green'
        - 'cap-color_Brown'
        - 'cap-color_Red'
        - 'cap-color_Pink'
        - 'cap-color_Buff'
        - 'cap-color_Purple'
        - 'cap-color_Cinnamon'
        - 'bruises_Bruises'
        - 'bruises_No Bruises'
        - 'gill-attachment_Free'
        - 'gill-attachment_Attached'
        - 'gill-spacing_Close'
        - 'gill-spacing_Crowded'
        - 'gill-size_Broad'
        - 'gill-size_Narrow'
        - 'gill-color_Black'
        - 'gill-color_Brown'
        - 'gill-color_Gray'
        - 'gill-color_White'
        - 'gill-color_Pink'
        - 'gill-color_Chocolate'
        - 'gill-color_Purple'
        - 'gill-color_Red'
        - 'gill-color_Buff'
        - 'gill-color_Green'
        - 'gill-color_Yellow'
        - 'gill-color_Orange'
        - 'stalk-shape_Enlarging'
        - 'stalk-shape_Tapering'
        - 'stalk-surface-above-ring_Smooth'
        - 'stalk-surface-above-ring_Fibrous'
        - 'stalk-surface-above-ring_Silky'
        - 'stalk-surface-above-ring_Scaly'
        - 'stalk-surface-below-ring_Smooth'
        - 'stalk-surface-below-ring_Fibrous'
        - 'stalk-surface-below-ring_Scaly'
        - 'stalk-surface-below-ring_Silky'
        - 'stalk-color-above-ring_White'
        - 'stalk-color-above-ring_Gray'
        - 'stalk-color-above-ring_Pink'
        - 'stalk-color-above-ring_Brown'
        - 'stalk-color-above-ring_Buff'
        - 'stalk-color-above-ring_Red'
        - 'stalk-color-above-ring_Orange'
        - 'stalk-color-above-ring_Cinnamon'
        - 'stalk-color-above-ring_Yellow'
        - 'stalk-color-below-ring_White'
        - 'stalk-color-below-ring_Pink'
        - 'stalk-color-below-ring_Gray'
        - 'stalk-color-below-ring_Buff'
        - 'stalk-color-below-ring_Brown'
        - 'stalk-color-below-ring_Red'
        - 'stalk-color-below-ring_Yellow'
        - 'stalk-color-below-ring_Orange'
        - 'stalk-color-below-ring_Cinnamon'
        - 'veil-color_White'
        - 'veil-color_Brown'
        - 'veil-color_Orange'
        - 'veil-color_Yellow'
        - 'spore-print-color_Brown'
        - 'spore-print-color_Black'
        - 'spore-print-color_Purple'
        - 'spore-print-color_Chocolate'
        - 'spore-print-color_White'
        - 'spore-print-color_Green'
        - 'spore-print-color_Orange'
        - 'spore-print-color_Yellow'
        - 'spore-print-color_Buff'
        - 'population_Numerous'
        - 'population_Abundant'
        - 'population_Scattered'
        - 'population_Several'
        - 'population_Solitary'
        - 'population_Clustered'
        - 'habitat_Grasses'
        - 'habitat_Meadows'
        - 'habitat_Urban'
        - 'habitat_Wood'
        - 'habitat_Paths'
        - 'habitat_Waste'
        - 'habitat_Leaves'
      target: 'class'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - classification_performance
      - cat_target_drift
    reference_file: ./datasets/reference_df.parquet
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
